### ISSUE TITLE
How to change the playable area in HFO?

### ISSUE THREAD

**Issue by CoolPhilChen** [LARG/HFO#76]
Hi @mhauskn ! As is written in your [paper](https://arxiv.org/abs/1511.04143), HFO is built on [RoboCup 2D simulator](https://github.com/rcsoccersim/rcssserver) by Hidehisa Akiyama, and you restricted the playable area to half of the entire field. I want to solve the problem using just sparse rewards, and I think the current size of the playable area, i.e. the half field, is still too large for quickly prototyping algorithms. Thus I want to further restrict the playable area, say to the penalty area. I looked through the HFO code, but still don't know how to do it? Could you give me some clues? Thanks a lot.

**Comment by mhauskn** [comment]
Here's a pointer to the decision logic used to decide when the ball is out of bounds:

https://github.com/mhauskn/rcssserver/blob/master/src/referee.cpp#L3058

You could implement a command line argument similar to the "ball_x_min/ball_x_max/ball_y_min/ball_y_max" to define the playable area instead of the ball initialization region. For reference these hook into the code at the following point:

https://github.com/mhauskn/rcssserver/blob/master/src/referee.cpp#L3231

Hope this helps!

**Comment by CoolPhilChen** [comment]
Great! Thanks a lot for your reply!

**Comment by CoolPhilChen** [comment]
For those who want to do the same thing, here is my example. You only need to do the following:

- https://github.com/CoolPhilChen/rcssserver/blob/5a20af22229f7bc3e4d2a20869ee02497b3e6ec5/src/referee.cpp#L3195

- https://github.com/CoolPhilChen/rcssserver/blob/5a20af22229f7bc3e4d2a20869ee02497b3e6ec5/src/referee.cpp#L3060
- https://github.com/CoolPhilChen/rcssserver/blob/5a20af22229f7bc3e4d2a20869ee02497b3e6ec5/src/referee.h#L714

**Comment by mhauskn** [comment]
Thank you for the informative writeup!
